name: create AWS infrastructure For hosting Angular App in ec2 instance
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/create_infra.yaml'
      - 'infra/**'
permissions:
  contents: read
  id-token: write
jobs:
  create_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for East US region audience
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
            audience: sts.amazonaws.com
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.7
      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform deployment
        run: terraform plan -out=tfplan

      - name: Apply Terraform deployment
        run: terraform apply -auto-approve tfplan